server:
  port: 2000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tindog
    username: root
    password: 1234

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 5umZ6__Lhex2mo0Zq_EH # 발급 받은 Client ID
            client-secret: jHJHp3IxnD # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:2000/login/oauth2/code/naver
            scope:
              - name
              - email             
            client-name: Naver

          kakao:
            client-id: 95e571ccdef498c2292ea09a52afbf24 # 발급 받은 Client ID
            client-secret:  ZYMVoIJbCUealLhlePqWystFlhSDDIXV # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - account_email
            redirect-uri: http://localhost:2000/login/oauth2/code/kakao
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

            # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정    

